.github/workflows/pr.yml
.github/workflows/pull-request.yml
.github/workflows/push.yml
.gitignore
functions/index.js

작성 중.
- github action script를 추가하였습니다.

Chore: added github action script

---

functions/models/area.js
functions/models/index.js
functions/models/order.js
functions/models/post.js
functions/models/scrap.js
functions/models/spot.js
functions/models/spot_photo.js
functions/models/user.js

[#6] 데이터베이스 모델 클래스 작성

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/service/postService.js

From #5 
- 최신 여행 후기 조회 컨트롤러 모듈 구현
- 최신 여행 후기 조회 서비스 모듈 구현
- 최신 여행 후기 조회 라우터 모듈 구현

[#5] 최신 여행 후기 조회 구현 

---

functions/models/area.js
functions/models/order.js
functions/models/post.js
functions/models/scrap.js
functions/models/spot.js
functions/models/spot_photo.js
functions/models/user.js
functions/service/postService.js

[FEAT] rename is_deleted to deleted_at

---

functions/api/routes/areaApi.js
functions/api/routes/index.js
functions/controller/areaController.js
functions/controller/index.js
functions/service/areaService.js
functions/service/index.js

From #15 
여행지 리스트 조회 컨트롤러 모듈 구현
여행지 리스트 조회 서비스 모듈 구현
여행지 리스트 조회 라우터 모듈 구현

[#15] 여행지 리스트 조회 기능

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/service/postService.js

- 여행지별 컨텐츠 미리보기 태그정보 조회
- 수정하지 않은 is_deleted 컬럼 이름 확인 (deletedAt)

[#21] 여행지별 컨텐츠 미리보기 태그정보 조회

---

functions/api/routes/index.js
functions/api/routes/orderApi.js
functions/controller/index.js
functions/controller/orderController.js
functions/models/index.js
functions/service/index.js
functions/service/orderService.js

#22 
- 구매한 컨텐츠 조회 컨트롤러 모듈 구현
- 구매한 컨텐츠 조회 서비스 모듈 구현
- 구매한 컨텐츠 조회 라우터 모듈 구현
-  orderDB, postDB, userDB 외래키 설정

[#22] 구매한 컨텐츠 조회 기능

---

functions/api/routes/index.js
functions/api/routes/orderApi.js
functions/api/routes/scrapApi.js
functions/controller/index.js
functions/controller/orderController.js
functions/controller/scrapController.js
functions/models/index.js
functions/service/index.js
functions/service/orderService.js
functions/service/scrapService.js

#28 
- 스크랩한 컨텐츠 조회 컨트롤러 모듈 구현
- 스크랩한 컨텐츠 조회 서비스 모듈 구현
- 스크랩한 컨텐츠 조회 라우터 모듈 구현
- scrapDB, postDB, userDB 외래키 설정

[#28] 스크랩한 컨텐츠 조회 기능

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/models/index.js
functions/service/postService.js

#35 
- 유저가 게시한 포스트 조회 컨트롤러 구현
- 유저가 게시한 포스트 조회 서비스 구현
- 유저가 게시한 포스트 조회 페이징 구현
- 유저가 게시한 포스트 조회 라우터 구현

[FEAT] 유저가 게시한 포스트 조회 기능

---

functions/controller/scrapController.js
functions/service/scrapService.js

[FEAT] 스크랩 정렬 기능 추가

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/service/postService.js

* 여행후기 컨텐츠 상세조회 서비스 모듈 구현
* 여행후기 컨텐츠 상세조회 컨트롤러 모듈 구현
* 여행후기 컨텐츠 상세조회 라우터 모듈 구현

[#30] 여행후기 컨텐츠 상세조회 API 구현

---

functions/api/routes/scrapApi.js
functions/controller/scrapController.js
functions/service/scrapService.js

[FEAT] 스크랩 추가 기능 구현

---

functions/controller/postController.js
functions/service/postService.js

#13 
- 추천 여행 일정, 최신 여행 일정 페이징 기능 추가

[#13] 컨텐츠 조회 API 페이징 기능 추가

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/service/postService.js

#55 
- 스크랩뷰 랜덤 포스트 조회 컨트롤러 추가
- 스크랩뷰 랜덤 포스트 조회 서비스 추가
- 스크랩뷰 랜덤 포스트 조회 라우터 설정

[FEAT] 스크랩뷰 랜덤 포스트 기능 추가

---

functions/service/orderService.js
functions/service/postService.js
functions/service/scrapService.js

nickname으로 내려주던 결과를 author로 수정하였습니다.

refactor: rename nickname field to author

---

functions/api/routes/postApi.js
functions/controller/postController.js
functions/package-lock.json
functions/package.json
functions/service/postService.js

#61 
스크랩 랜덤 기능 is_purchared 옵션 추가

[FEAT] 스크랩 랜덤 is_purchared 추가

---

functions/lib/pagination.js
functions/service/orderService.js
functions/service/postService.js
functions/service/scrapService.js
functions/service/userService.js

- 사용하지 않거나
- 로직을 단순화 시킬 수 있거나
- 오류를 일으킬 수 있는
부분들에 대해 리팩터링 진행했습니다.

refactor: 코드 리팩터링

---

.gitignore
functions/lib/util.js
functions/package-lock.json
functions/package.json
functions/utils/slackBot.js

Error 시에 Slack bot을 통해 알림을 받을 수 있도록 구성하였습니다.

feat: slack webhook

---

functions/api/index.js
functions/controller/areaController.js
functions/controller/authController.js
functions/controller/index.js
functions/controller/orderController.js
functions/controller/postController.js
functions/controller/scrapController.js
functions/controller/userController.js
functions/package-lock.json
functions/package.json

- remove try/catch of controller
- use middleware try/catch check
- add sentry

feat: add Sentry

---

functions/api/index.js
functions/controller/authController.js
functions/lib/util.js

- 알람 메시지가 구체적이지 않아서 수정하였습니다.
- 회원가입 시, 회원가입 알림이 오도록 수정하였습니다.

Feature: slack specific msg
